# Selected browser (chrome/yandex)
selected.browser=chrome

# Browser configurations
browser.chrome.name=chrome
browser.chrome.path=src/main/resources/chromedriver-win32/chromedriver.exe

browser.yandex.name=yandex
browser.yandex.path=/path/to/yandexdriver
